2025-03-02 19:14:06,508 ERROR: Exception on /map [GET] [in /Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephentrento/flask_app/.venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/stephentrento/flask_app/app/routes.py", line 98, in map
    return render_template('map.html', form=form, user_access_level=current_user.access_level, user_id=current_user.id, form2=form2)
                                                                                                       ^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
2025-03-02 19:25:51,359 INFO: Our Camden startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-03-02 20:15:15,194 INFO: Our Camden startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-03-02 20:16:26,939 INFO: Our Camden startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-03-02 20:17:07,645 INFO: Our Camden startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-03-02 20:17:12,358 INFO: Our Camden startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-03-02 20:19:52,173 INFO: Our Camden startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-03-02 20:21:36,278 INFO: Our Camden startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
2025-03-02 20:26:57,605 INFO: Our Camden startup [in /Users/stephentrento/flask_app/app/__init__.py:51]
